# Site settings
title: "گاه‌نبشت‌های آرمان رادمنش"
motto: ""
author: Arman Radmanesh
email: radmanesh@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.armanradmanesh.com" # the base hostname & protocol for your site
keywords: "کامپیوتر، برنامه‌نویسی، طراحی وب، علم، ساخت برنامه تحت وب"
copyright: "Commons Attribution 4.0 International"
robot: ""
description: > # this means to ignore newlines until "baseurl:"
  فضایی برای انتشار افکار و مطالبی پراکنده در رودخانه‌ی پریشان زندگی


twitter_username: radmanesh
github_username:  radmanesh
fullname: "آرمان رادمنش"
favicon: "assets/img/favicon.png"

permalink: :title.html

timezone: Iran/Tehran

paginate: 3
paginate_path: "/page:num/"

tag_page_layout: tag_page
tag_page_dir: tag

plugins:
  - jekyll-jalali
  - jekyll-hinduarabic
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-markright

markdown: Markright

collections:
  projects:
    output: true

#disqus: false
#disqus_shortname:
#google_analytics_id: UA-109137890-1

debate: true
debate_acc: 'a3eaa4df18e01cfbeb182ce280ef5bfe'
